SWP\Bundle\ContentBundle\Doctrine\ORM\ContentList:
    type:  entity
    table: swp_content_list
    fields:
        tenantCode:
            type: string
    oneToMany:
        items:
            targetEntity: SWP\Component\ContentList\Model\ContentListItemInterface
            mappedBy: contentList
            cascade: ["all"]