SWP\Bundle\ContentBundle\Doctrine\ORM\ContentList:
    type:  entity
    table: swp_content_list
    fields:
        tenantCode:
            type: string
        author:
            type: string
            nullable: true
    manyToOne:
        route:
            targetEntity: SWP\Bundle\ContentBundle\Doctrine\ORM\Route
            joinColumn:
                name: route_id
                referencedColumnName: id
                nullable: true
                onDelete: "SET NULL"
    oneToMany:
        items:
            targetEntity: SWP\Component\ContentList\Model\ContentListItemInterface
            mappedBy: contentList
            orphanRemoval: true
            cascade: ["all"]
