monolog:
    channels:
        - swp_asset_download
    handlers:
        swp_asset_download:
            level:    debug
            type:     rotating_file
            path:     '%kernel.logs_dir%/swp_asset_download_%kernel.environment%.log'
            max_files: 7
            channels: swp_asset_download
        swp_rule:
            level:    debug
            type:     rotating_file
            path:     '%kernel.logs_dir%/swp_rule_%kernel.environment%.log'
            max_files: 7
            channels: swp_rule
        swp_validators:
            level:    debug
            type:     rotating_file
            path:     '%kernel.logs_dir%/swp_validators_%kernel.environment%.log'
            max_files: 7
            channels: swp_validators
