parameters:
    env(SENTRY_DSN): false

sentry:
    dsn: '%env(resolve:SENTRY_DSN)%'
    options:
        environment: '%kernel.environment%'
        release: '2.0.2'
        excluded_exceptions: #exclude validation errors
            - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
