language: php
services:
  - redis-server
matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: DOCTRINE_CACHE_DRIVER="redis"
    - php: 5.6
      env: DOCTRINE_CACHE_DRIVER="redis"
    - php: 7.0
      env: DOCTRINE_CACHE_DRIVER="array"
    - php: hhvm
      env: DOCTRINE_CACHE_DRIVER="array"
  allow_failures:
    - php: hhvm

before_script:
  - if [[ $TRAVIS_PHP_VERSION =~ 5.[56] ]] ; then echo 'extension="redis.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
  - if [[ $TRAVIS_PHP_VERSION =~ 5.[56] ]] ; then cat ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini|grep redis; fi;
  - phpenv rehash
  - composer install --no-interaction --prefer-source

script:
  - bin/phpspec run --format=pretty
  - phpunit -c app/

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
