php:
    build: docker/php-fpm
    expose:
        - 9000:9000
    volumes:
        - .:/var/www/webrenderer
        - logs/nginx/:/var/log/nginx
nginx:
    build: docker/nginx
    ports:
        - 80:80
    links:
        - php
    volumes:
        - .:/var/www/webrenderer
        - logs/nginx/:/var/log/nginx

renderer:
    build: docker/renderer
    links:
        - php
        - nginx
    volumes:
        - .:/var/www/webrenderer
        - logs/webrenderer:/var/www/webrenderer/app/logs
    tty: true