services:
    swp_renderer_routing_loader:
        class: SWP\WebRendererBundle\Routing\Loader\PagesLoader
        arguments:
            - @doctrine
        tags:
            - { name: routing.loader }
