imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem
    profiler:
        enabled: true
        collect: false

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     "%kernel.cache_dir%/test.db3"
doctrine_phpcr:
    session:
        backend:
            caches:
                meta: doctrine_cache.providers.metadata_array
                nodes: doctrine_cache.providers.nodes_array

liip_functional_test: ~

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

liip_theme:
    themes: ["theme_test"]
    active_theme: "theme_test"
    load_controllers: false
    autodetect_theme: true
    path_patterns:
        app_resource:
            - "%%app_path%%/themes/%%current_theme%%/%%current_device%%/%%template%%"
