imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem
    profiler:
        collect: false
doctrine:
    dbal:
        driver: pdo_sqlite
        path:     %kernel.cache_dir%/test.db

liip_functional_test: ~

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

liip_theme:
    themes: ['theme_test',]
    active_theme: 'theme_test'
    load_controllers: false
    autodetect_theme: true
    path_patterns:
        app_resource:
            - %%app_path%%/themes/%%current_theme%%/%%current_device%%/%%template%%
