parameters:
    env(SWP_DOMAIN): localhost
    cache_servers:
        - localhost
    superdesk_servers:
        - localhost:3000
    themes.upload_dir: "%kernel.cache_dir%"
    env(ELASTICA_INDEX_NAME): 'swp_index-test'
