swp_webrendere_pages:
    resource: .
    type: pages

swp_webrenderer:
    resource: "@SWPWebRendererBundle/Controller/"
    type:     annotation

swp_updater:
    resource: "@SWPUpdaterBundle/Resources/config/routing.yml"
    prefix:   /
