SWP\Bundle\TemplatesSystemBundle\Model\ContainerData:
    exclusion_policy: ALL
    properties:
        key:
            expose: true
            groups: [api]
            type: string
        value:
            expose: true
            groups: [api]
            type: string
