SWP\Bundle\TemplatesSystemBundle\Model\ContainerWidget:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [api]
            type: integer
        widget:
            expose: true
            groups: [api]
            type: SWP\Bundle\TemplatesSystemBundle\Model\WidgetModel
        position:
            expose: true
            groups: [api]
            type: string
