parameters:
    swp_content_bundle.article.manager.class: SWP\Bundle\ContentBundle\Doctrine\ArticleManager

services:
    swp.manager.article.phpcr:
        class: '%swp_content_bundle.article.manager.class%'
        arguments:
            - '@swp.object_manager.article'
            - '@swp.repository.article'
            - '@swp_multi_tenancy.path_builder'
