SWP\Bundle\ContentBundle\Doctrine\ORM\ContentList:
    exclusion_policy: ALL
    properties:
        author:
            expose: true
            type: string
        route:
            expose: true
    relations:
        - rel: self
          href:
                route: swp_api_content_show_lists
                parameters:
                    id: expr(object.getId())
