SWP\Bundle\ContentBundle\Model\File:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [api]
            type: string
        fileExtension:
            expose: true
            groups: [api]
        assetId:
            expose: true
            groups: [api]
    relations:
        -
            rel: download
            href:
                route: swp_media_get
                parameters:
                    mediaId: expr(object.getAssetId())
                    extension: expr(object.getFileExtension())
