SWP\Bundle\ContentBundle\Model\RelatedArticle:
  exclusion_policy: ALL
  properties:
    article:
      expose: true
            groups: [api]
    createdAt:
      expose: true
            groups: [api]
    updatedAt:
      expose: true
            groups: [api]
