SWP\Bundle\ContentBundle\Model\Image:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [api]
            type: integer
        width:
            expose: true
            groups: [api]
        height:
            expose: true
            groups: [api]
        fileExtension:
            expose: true
            groups: [api]
        assetId:
            expose: true
            groups: [api]
            type: string
