SWP\Bundle\ContentBundle\Model\Route:
    exclusion_policy: ALL
    properties:
        templateName:
            expose: true
        type:
            expose: true
        name:
            expose: true
        slug:
            expose: true
        cacheTimeInSeconds:
            expose: true
            type: integer
        articlesTemplateName:
            expose: true
            type: string
        position:
            expose: true
            type: integer
        lft:
          expose: true
          type: integer
        rgt:
          expose: true
          type: integer
        level:
            expose: true
            type: integer
        children:
            expose: true
        parent:
            expose: true
            type: integer
            accessor:
                getter: getParentId
    relations:
        - rel: self
          href:
                route: swp_api_content_show_routes
                parameters:
                    id: expr(object.getId())
        - rel: parent
          href:
                route: swp_api_content_show_routes
                parameters:
                    id: expr(object.getParent().getId())
          exclusion:
                exclude_if: expr(null === object.getParent())
