SWP\Bundle\ContentBundle\Model\Keyword:
    exclusion_policy: ALL
    properties:
        name:
            expose: true
            groups: [api]
        slug:
            expose: true
            groups: [api]
