SWP\Bundle\ContentBundle\Model\ArticleMedia:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [api]
            type: string
        file:
            expose: true
            groups: [api]
        image:
            expose: true
            groups: [api]
        renditions:
            expose: true
            groups: [api]
        byLine:
            expose: true
            groups: [api]
        body:
            expose: true
            groups: [api]
            serialized_name: altText
        description:
            expose: true
            groups: [api]
        usageTerms:
            expose: true
            groups: [api]
        headline:
            expose: true
            groups: [api]
        copyrightNotice:
            expose: true
            groups: [api]
            type: string
        copyrightHolder:
            expose: true
            groups: [api]
            type: string
    relations:
        -
            rel: download
            href:
                route: swp_media_get
                parameters:
                    mediaId: "expr(object.getImage() ? object.getImage().getAssetId() : object.getFile().getAssetId())"
                    extension: "expr(object.getImage() ? object.getImage().getFileExtension() : object.getFile().getFileExtension())"
            exclusion:
                exclude_if: "expr(null === object.getFile() && null === object.getImage())"