SWP\Bundle\ContentBundle\Model\ArticleSource:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [api]
            type: integer
        name:
            expose: true
            groups: [api]
            type: string
        createdAt:
            expose: true
            groups: [api]
            type: DateTime
        updatedAt:
            expose: true
            groups: [api]
            type: DateTime
