SWP\Bundle\ContentBundle\Model\Slideshow:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [api]
        code:
            expose: true
            groups: [api]
        article:
            expose: true
            groups: [api]
        createdAt:
            expose: true
            groups: [api]
        updatedAt:
            expose: true
            groups: [api]
        items:
            expose: true
            groups: [api]
            type: array<SWP\Bundle\ContentBundle\Model\SlideshowItemInterface>
