SWP\Bundle\ContentBundle\Model\Image:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: string
        width:
            expose: true
        height:
            expose: true
        fileExtension:
            expose: true
        assetId:
            expose: true
