SWP\Bundle\ContentBundle\Doctrine\ODM\PHPCR\Article:
    repositoryClass: SWP\Bundle\ContentBundle\Doctrine\ODM\PHPCR\ArticleRepository
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
        loggable: true
    referenceable: true
    parentdocument: parent
    nodename: slug
    id: id
    fields:
        body:
            type: string
        title:
            type: string
        templateName:
            type: string
        locale:
            type: string
        status:
            type: string
        createdAt:
            type: date
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: date
            nullable: true
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: date
            nullable: true
    referenceOne:
        route:
            targetDocument: "\\SWP\\Bundle\\ContentBundle\\Doctrine\\ODM\\PHPCR\\Route"
            strategy: hard
