SWP\Bundle\ContentBundle\Doctrine\ODM\PHPCR\Article:
    repositoryClass: SWP\Bundle\ContentBundle\Doctrine\ODM\PHPCR\ArticleRepository
    referenceable: true
    parentdocument: parent
    nodename: slug
    id: id
    fields:
        body:
            type: string
        title:
            type: string
    referenceOne:
        route:
            targetDocument: "\\SWP\\Bundle\\ContentBundle\\Doctrine\\ODM\\PHPCR\\Route"
            strategy: hard
