SWP\TemplateEngineBundle\Model\ContainerWidget:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
        widget:
            expose: true
            type: SWP\TemplateEngineBundle\Model\Widget
        position:
            expose: true
            type: string
