SWP\TemplateEngineBundle\Model\Container:
    relations:
        -   
            rel: self
            href:
                route: swp_api_templates_get_container
                parameters:
                    id: expr(object.getId())