services:
    swp_renderer.phpcr.initializer:
        class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
        arguments:
            - SWP ContentBundle paths
            - [ "/swp/content", "/swp/routes" ]
        tags:
            - { name: "doctrine_phpcr.initializer" }

    swp_template_engine.loader.article:
        class: SWP\ContentBundle\Loader\ArticleLoader
        arguments:
            - %kernel.root_dir%
            - "@service_container"
        tags:
            - { name: swp.meta_loader }

    document_manager:
        alias: doctrine_phpcr.odm.document_manager

    swp_content_bundle.factory.knp_paginator_representation:
        class: SWP\ContentBundle\Factory\KnpPaginatorRepresentationFactory
        arguments:
            - 'page'
            - 'limit'

    swp_content_bundle.listener.link_request:
        class: SWP\ContentBundle\EventListener\LinkRequestListener
        arguments:  ["@controller_resolver", "@router"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    swp_pagination_rep:
        alias: swp_content_bundle.factory.knp_paginator_representation
