SWP\Bundle\FacebookInstantArticlesBundle\Model\Page:
    type: mappedSuperclass
    table: swp_fbia_pages
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        pageId:
            type: string
        name:
            type: string
        accessToken:
            type: string
            nullable: true
    manyToOne:
        application:
            targetEntity: SWP\Bundle\FacebookInstantArticlesBundle\Model\ApplicationInterface
            joinColumn:
                name: application_id
                referencedColumnName: id
                nullable: true
