SWP\Component\Revision\Model\Revision:
    exclusion_policy: ALL
    properties:
        createdAt:
            expose: true
            groups: [api]
            type: DateTime
        updatedAt:
            expose: true
            groups: [api]
            type: DateTime
        isActive:
            expose: true
            groups: [api]
            type: boolean
        status:
            expose: true
            groups: [api]
        uniqueKey:
            expose: true
            groups: [api]
    relations:
        -   rel: current
            href:
                route: swp_api_templates_revision_current
        -   rel: previous
            href:
                route: swp_api_templates_revision_single
                parameters:
                    id: "expr(object.getPrevious().getId())"
            exclusion:
                exclude_if: "expr(null == object.getPrevious())"
