services:
    swp_facebook.manager:
        class: SWP\Bundle\FacebookInstantArticlesBundle\Manager\FacebookManager
    swp_facebook.instant_articles_manager:
        class: SWP\Bundle\FacebookInstantArticlesBundle\Manager\FacebookInstantArticlesManager